# Generated by Django 4.2.19 on 2025-02-22 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_score_locationrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationrating',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.location'),
        ),
    ]
